/* Files are of two types in HDD(Hard Disk Drive)
    1.Program Files - "Notepad.exe"
    2.Data Files - "my.txt" (these are generated by the program files)
*/

/* Number System- 
    Binary(X2) - 0,1
    Decimal(X10) - 0,1,2,3,4,5,6,7,8,9
    Octal(X8) - 0,1,2,3,4,5,6,7
    HexaDecimal(X16) - 0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F
*/

// Human Language -> Programming Language -(Compiler/interpreter)-> Machine language 
// High level language - programming language
// Low Level Language - Assembly level language , Machine language

/*
    Compiler vs Interpreter 

    Compiler - faster 
             - While running exe file is used , not cpp file (and here source code is of no use now)
             - When we recompile and execute - a whole new exe file is used
    Interpreter - error in 1 line still execute (easier) - line by line translate and execute
    Hybrid - Java,C# 
           - lang -(compiler)-> bytecode -(JVM java virtual machine)-> Machine code

    Process - 
    1. Check errors
    2. Convert into Machine code(MC)
    3. Execution (Compiler (X) and Interpreter (ok))
*/

/*
    Program Development
    1. Monolithic Program (basic)
    2. Procedural/Modular (fucntions)
    3. Modular (structures)
    4. Object Oriented (classes)
*/

/*
    FlowChart (input -> process -> output)

    Oval - Start/Stop
    Arrow - flow
    Rhombus - I/P and O/P
    Rectangle - Process 
    Diamond - decision
*/

// IDE - Integrated Development Environment - eg. VSCode

/*
    Steps for Program Development and Execution - 

    Development
        1. Editing 
        2. Compiling 
        3. Linking Library
    4. Loading - HDD to main memory
    5. Execution
*/

/*
    Stack - For variale creation
    Heap - For dynamic memory allocation
    Code Section - For program itself

    HDD - first.cpp
        - first.exe (this is brought into main memory eg. code section)
*/

// #include <iostream> - header file - Machine code is available here
// in the header file <iostream> - Cin and Cout functions are present 
//instead of using std::cout and std::cin eveywhere we can use the line - "using namespace std;"
